# Generated by Django 3.2.3 on 2022-12-10 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('postal', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('bathroom_count', models.FloatField(max_length=250)),
                ('bedroom_count', models.IntegerField()),
                ('square_footage', models.IntegerField()),
                ('visible', models.BooleanField()),
                ('featured', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Prop_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_status', models.CharField(max_length=20)),
                ('prop_status_descr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_type_name', models.CharField(max_length=30)),
                ('prop_type_descr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdiv_name', models.CharField(max_length=50)),
                ('subdiv_descr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=51)),
                ('lastname', models.CharField(max_length=51)),
                ('address', models.CharField(max_length=101)),
                ('useremail', models.EmailField(blank=True, max_length=70, unique=True)),
                ('weburl', models.CharField(max_length=101)),
                ('username', models.CharField(max_length=50, null=True)),
                ('mobile', models.CharField(max_length=50, null=True)),
                ('aboutme', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_image_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Image')),
                ('listing', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='accounts.listing')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='prop_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.prop_status'),
        ),
        migrations.AddField(
            model_name='listing',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.property_type'),
        ),
        migrations.AddField(
            model_name='listing',
            name='subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subdivision'),
        ),
    ]
