# Generated by Django 4.1.3 on 2022-12-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=51)),
                ('lastname', models.CharField(max_length=51)),
                ('address', models.CharField(max_length=101)),
                ('useremail', models.EmailField(blank=True, max_length=70, unique=True)),
                ('postal', models.IntegerField()),
                ('weburl', models.CharField(max_length=101)),
                ('password', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
