# Generated by Django 4.1.3 on 2022-12-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=51)),
                ('lastname', models.CharField(max_length=51)),
                ('address', models.CharField(max_length=101)),
                ('useremail', models.EmailField(blank=True, max_length=70, unique=True)),
                ('weburl', models.CharField(max_length=101)),
                ('username', models.CharField(max_length=50, null=True)),
                ('mobile', models.CharField(max_length=50, null=True)),
                ('aboutme', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
